name: Golang Checker Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.1

      - name: Format
        run: go fmt ./...
      - name: Go Fix
        run: go fix ./...
      - name: Build
        run: go build -v ./...
